import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
  return (
    <Html lang="en">
      <Head>
      <meta charSet="utf-8" />
					<meta httpEquiv="X-UA-Compatible" content="IE=edge" />
					<link rel="manifest" href="/manifest.json" />
					{/* <!-- Required meta tags for responsive --> */}
					<meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no" />
					{/* page description */}
					<meta name="description" content="Generated by create next app" />
					<meta name="keywords" content="Keywords" />
					<meta name="msapplication-TileColor" content="#ffffff" />
					<meta name="msapplication-TileImage" content="/ms-icon-144x144.png" />
					<meta name="theme-color" content="#ffffff" />
					<meta name="application-name" content="Next Js PWA App" />
					<meta name="apple-mobile-web-app-capable" content="yes" />
					<meta name="apple-mobile-web-app-status-bar-style" content="default" />
					<meta name="apple-mobile-web-app-title" content="Next Js PWA App" />
					<meta name="format-detection" content="telephone=no" />
					<meta name="mobile-web-app-capable" content="yes" />
					<meta name="msapplication-config" content="icons/browserconfig.xml" />
					<meta name="msapplication-TileColor" content="#ffffff" />
					<meta name="msapplication-tap-highlight" content="no" />
					{/* <!-- Twitter Card data --> */}
					<meta name="twitter:card" content="summary" />
					<meta name="twitter:url" content="#" />
					<meta name="twitter:title" content="Next Js PWA App" />
					<meta name="twitter:description" content="#" />
					<meta name="twitter:image" content="#" />
					<meta name="twitter:creator" content="#" />
					{/* <!-- Open Graph data --> */}
					<meta property="og:type" content="website" />
					<meta property="og:title" content="IFAD IMPL APP" />
					{/* <meta property="og:description" content="Next Js PWA App" /> */}
					{/* <meta property="og:site_name" content="Next Js PWA App" /> */}
					{/* <meta property="og:url" content="#" /> */}
					{/* <meta property="og:image" content="#" /> */}
					{/* <!-- gmail verification --> */}
					<meta name="google-site-verification" content="" />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}
